### PR TITLE
add defun-nodecl

### PR DESCRIPTION
**Pull request by iZarif**

### CODE REVIEW

**Comment by makuto** [comment]
Resolved with 9930cd2. I'm going to change the header output rules to make the hack in this PR go away.

**Comment by makuto** [comment]
By the way, were you wanting this feature because declaring classes and member functions isn't exposed yet? Or do you need to define member functions for classes that must be declared in a .h/.hpp file?

**Comment by iZarif** [comment]
> By the way, were you wanting this feature because declaring classes and member functions isn't exposed yet? Or do you need to define member functions for classes that must be declared in a .h/.hpp file?

Because declaring classes and member functions isn't exposed

**Comment by makuto** [comment]
I'll create a generator that can handle classes with members then. It'll look something like this:
``` lisp
(defclass my-class
  my-var int
  (defun my-member-func (&return bool)
    (return true)))
```

**Comment by makuto** [comment]
3b0755e adds slightly smarter header `#include`, but the right solution here is still to create the class generator, which I'm doing next.

**Pull request closed without merging**
